### ISSUE TITLE
Static MAC Address and DHCPD.CONF

### ISSUE THREAD

**Issue by ibenrodriguez** [pdellaert/vSphere-Python#3]
We had something like this with pyshpere API a few years ago. Would these two features be possible to integrate? These are needed for IP Address assignment to the new VMs being setup through clone process so they do not get a random MAC or IP Address.

For each machine assign a static IP Address and MAC Address to the VM for example:
 
S06241V9F
 
Character position:
1.  “S” for swimlane decimal from 1 to 6 corresponding to chassis
2.  10’s for swimlane ID
3.  1’s for swimlane ID
4.  “H” for hypervisor decimal from 1 to 24
5.  10’s for hypervisor ID
6.  1’s for hypervisor ID
7.  “V” for virtual machine hex from 00 to FF
8.  16’s for hypervisor ID
9.  1’s for hypervisor ID

Virtual Swimlane to VM MAC and IP mapping
Count, VM_NAME, VM_MAC, VM_IP
# row number 0001
host S01H01V01.vct.lab.com {
hardware ethernet 00:50:56:00:01:01;
fixed-address 192.168.1.1;
option host-name "S01H01V01.vct.lab.com";
filename "pxelinux.0";
# row number 0002
host S01H01V02.vct.lab.com {
hardware ethernet 00:50:56:00:01:02;
fixed-address 192.168.1.2;
option host-name "S01H01V02.vct.lab.com";
filename "pxelinux.0";

**Comment by pdellaert** [comment]
So, if i'm correct, you would want to be able to provide a list of vm names with a mac and an ip for each, and the script just clones the correct template to each of the vms in that list?

Just dumping my brain here:
This should be possible to implement by allowing the user to import a CSV file with those fields. The only thing i might struggle with: Combining the functionality of outputting the actual IP address of the VM after cloning (and booting) it, and outputting the IP address in the CSV. Might make it so that a CSV can be provided and if the CSV contains 2 fields (VM Clone name,MAC) the script would output the 'actual' IP address returned by the running VM (through vsphere); if the CSV contains 3 fields (VM Clone name, MAC, IP), it would return the IP of the CSV.

If you just want to be able to setup your DHCP configuration, without determining the specific VM name, MAC or IP address set during cloning, than you could do this using a post script, IF i add the mac address as an extra variable when the post script is called.

**Comment by pdellaert** [comment]
I've added some extra functionality, this should provide you with the necessary feature...

You can specify a CSV file with the -C flag, and in the CSV you can add lines like:
```
"S01H01V01";"Development";"IT";"00:50:56:00:01:01";""
```
This would place the VM in the Development Resource Pool and the IT folder. It will also set the mac address of the first nic it encounters to the specified MAC. (and it wouldn't run a post-processing script, as that parameter is empty)
